services:
  db:
    container_name: 'database'
    image: 'postgres:16'
    restart: always
    environment:
      - 'POSTGRES_DB=msngr'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=msngradmin'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - ./docker_db:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  app:
    container_name: simplemsngr
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db